### ISSUE TITLE
something wrong? 

### ISSUE THREAD

**Issue by LoweDavince** [sikang/motion_primitive_library#1]
Hi ,
when i change the start and goal as following and set the mode to velocity control, something wrong occurs. Is it my improper use?
oh, the test code is  test_planner_2d.cpp 
```c++  
  Waypoint2D start, goal;
  //start.pos = Vec2f(reader.start(0), reader.start(1));
  start.pos = Vec2f(6.77, -3.5);
  start.vel = Vec2f::Zero();
  start.acc = Vec2f::Zero();
  start.jrk = Vec2f::Zero();
  start.yaw = 0;
  start.use_pos = true;
  start.use_vel = false;
  start.use_acc = false;
  start.use_jrk = false;
  start.use_yaw = false;

  //goal.pos = Vec2f(reader.goal(0), reader.goal(1));
  goal.pos = Vec2f(28, -1.1);
  goal.vel = Vec2f::Zero();
  goal.acc = Vec2f::Zero();
  goal.jrk = Vec2f::Zero();
  goal.yaw = 0;
  goal.control = start.control;

  // Initialize control input
  decimal_t u = 0.1;
```
![1546503464 1](https://user-images.githubusercontent.com/6355565/50629186-7e3d1280-0f76-11e9-957f-9a530a540a2b.png)

**Comment by sikang** [comment]
Hi, can you show the full set up for this test? I got the attached result which is different from what you have using the provided snippet. 
![test_planner_2d](https://user-images.githubusercontent.com/1514647/50655180-2eddee80-0f44-11e9-87fc-212350bccf2d.jpg)

**Comment by LoweDavince** [comment]
Thank u for your reply so quickly . 
I re-download the code and just change the start and goal , still get the same wrong result as before.
![1546565268 1](https://user-images.githubusercontent.com/6355565/50670053-f271c780-1003-11e9-89e1-bee0471322c7.png)
But when I use another computer , I get the correct result .
So its my computer's(debian 8) problem, or maybe the third-party's fault.

**Comment by sikang** [comment]
I see, is that the ARM processor? The collision checking can be problematic, but for x64 it should be fine.

**Comment by LoweDavince** [comment]
也没，我用的虚拟机
